---
title: "Task 8"
Author: "April Armes"
output: github_document 

---

## Write a funtion that fulfills the following criteria: 
  * It should be tidyverse compatible (i.e., the first argument must be a data frame)
  
  * It should add two arbitrary columns of the data frame (specified by the user) and put them in a new column of that data frame, with the name of the new column specified by the user
  
  * It should throw an informative warning if any invalid arguments are provided. Invalid arguments        might include:
  
      * The first argument is not a data frame
 
      * Less than two valid columns are specified to add (e.g., one or both of the column names isn't in       the supplied data frame)
  
      * The columns specified are not numeric, and therefore can't be added - use tryCatch() for this
  
  * If the columns to add aren't valid but the new column name is, the function should create a column of NA values


```{r}
#Libraries needed for this script --------------------------------------------
library(tidyverse)
library(dplyr)

#This script accomplishes task 8 part I --------------------------------------

#This function uses 4 arguments, the first being the data frame, i, j, k being columns.
grades_add <- function(df, i, j, k, l) { 
  
  ## this checks the arguments for errors 
  
  #This creates a warning if first argument does not contain a dataframe 
  if(is.data.frame(df) != TRUE) {
    stop("Argument df is not a data frame")
    }
    
  
  
  if((is.vector(df[[i]])) != TRUE || (is.vector(df[[j]])) != TRUE || (is.vector(df[[k]])) != TRUE) {
    stop("column does not belong to data frame")
    }
  
  
  
  #checks that columns are numeric
  tryCatch(
    if(!is.numeric(df[[i]]) | !is.numeric(df[[j]]) | !is.numeric(df[[k]])) {
      warning("One of the specified columns (i, j, k) is not numeric")
      }
  )
  
  #This function adds column i and j and creates a new column, k. And returns final data frame 
  z <- df[ , i] + df[ , j] + df[ , k]
  df[ , l] <- z
  df
}

  #calling the function
x <- read.csv("../data/grades2.csv")
t <- grades_add(x, "Quiz", "Wksht", "Exam1", "SemSum")
t


```